apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: replacements-fn-config
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: kptfile.kpt.dev
    fieldPath: data.name
  targets:
  - select:
      group: configsync.gke.io
      kind: RootSync
      name: nephio-workload-cluster-sync
    fieldPaths:
    - spec.git.repo
    options:
      delimiter: /
      index: 4
