apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: nephio-5gc
    app.kubernetes.io/part-of: nephio-5gc
    app.kubernetes.io/version: tbd
  name: nephio-5gc-controller-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nephio-5gc-controller-controller-role
subjects:
- kind: ServiceAccount
  name: nephio-5gc-controller
  namespace: nephio-system
