apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: nephio-5gc
    app.kubernetes.io/part-of: nephio-5gc
    app.kubernetes.io/version: tbd
  name: nephio-5gc-controller-leader-election-role-binding
  namespace: nephio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nephio-5gc-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: nephio-5gc-controller
