apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  annotations:
    config.kubernetes.io/depends-on: apiextensions.k8s.io/CustomResourceDefinition/configmanagements.configmanagement.gke.io
spec:
  enableMultiRepo: true
